---
title: "R Notebook"
output: html_notebook
---

[Tutorial](https://eriqande.github.io/rep-res-web/lectures/making-maps-with-R.html)
https://evodify.com/rivers-map-in-r/
```{r}
library(ggplot2)
library(maps)
library(ggmap)
library(mapdata)


#quick example
map(col="grey80", border = "grey40", fill = TRUE,
  xlim = c(10, 36), ylim = c(50, 68), mar = rep(0.1, 4))
box()
points(25.615672,58.977768,col=2,pch=18)



#theme
#code to drop axes and ticks but keep guides and legends
  ditch_the_axes <- theme(
  axis.text = element_blank(),
  axis.line = element_blank(),
  axis.ticks = element_blank(),
  panel.border = element_blank(),
  panel.grid = element_blank(),
  axis.title = element_blank()
  )
  
#map california
states <- map_data("state")
dim(states)
  #check all states
  ggplot(data = states) + 
  geom_polygon(aes(x = long, y = lat, fill = region, group = group), color = "white") + 
  coord_fixed(1.3) +
  guides(fill=FALSE)  # do this to leave off the color legend
#subset CA
ca_df <- subset(states, region == "california")

head(ca_df)
tail(ca_df)
  #further subset to set county lines
  counties <- map_data("county")
  ca_county <- subset(counties, region == "california")
  head(ca_county)
  #plot with no lines
  ca_base <- ggplot(data = ca_df, mapping = aes(x = long, y = lat, group = group)) + 
  coord_fixed(1) + 
  geom_polygon(color = "black", fill = "gray")
  ca_base + theme_nothing()
  #plot with county lines
  ca_base_county<-ca_base + #theme_nothing() + #drops coordinates and grid
  geom_polygon(data = ca_county, fill = NA, color = "white") +
  geom_polygon(color = "black", fill = NA)  # get the state border back on top

  #add rivers
  ca_base_county + geom_sf(mapping = aes(group = group, x=long, y=lat), data = CAriver.crs) +
  coord_sf()
  
   #zoom in
    ca_base_county + coord_fixed(xlim = c(-124.5, -119.0),  ylim = c(37.5,42), ratio = 1.1)+ theme_bw() +
    ditch_the_axes
#read in river data
    CAwater<-st_read(dsn = here("NHD_Major_Rivers"))
    CAriver<-st_zm(CAwater, drop = T, what = "ZM") #drop M level to be able to use--not sure why
    #plot just river data
    ggplot() +
    geom_sf(mapping = aes(colour = mainpath), data = CAriver) +
    coord_sf()
    #transform coordinates to match google WGS84---not working still and don't need to do for overlaying
    #CAriver.crs<- st_transform(CAriver,
    #CRS("+proj=longlat +datum=WGS84"))
  #read in resevoir data
    CArez<-st_read(dsn = here("NHD_Major_Lakes_and_Reservoirs"))
    CArez<-st_zm(CArez, drop = T, what = "ZM") #drop M level to be able to use--not sure why
    #plot just river data
    ggplot() +
    geom_sf( data = CArez) +
    coord_sf()
#delta
    CAdelta<-st_read(dsn = here("Delta"))
    #CArez<-st_zm(CArez, drop = T, what = "ZM") #drop M level to be able to use--not sure why
    #plot just river data
    ggplot() +
    geom_sf( data = CAdelta) +
    coord_sf() 
    
#plot locations
    locs<-tibble(name = c("Delta Entry", "RBDD", "LSNFH", "Shasta Dam", "Keswick Dam", "Battle Creek", "Sacramento", "Caldwell Park"), 
           lat = c(38.581107,40.146709, 40.716690, 40.718939, 40.612332, 40.367241,38.5816, 40.592527),
           long = c(-121.508072,-122.154110,-122.415975,-122.418626,-122.445812, -122.169962,-121.4944, -122.391859),
           ref = c("reciever", "reciever", "hatchery", "dam", "dam", "hatchery", "city", "hatchery"))
    
#to plot rivers over basemap
 ggplot()+
   geom_polygon(data=ca_df, mapping = aes(x = long, y = lat, group = group), color = "black", fill = "transparent")+
   geom_sf( data = CAriver, color= if_else(CAriver$gnis_name == "Sacramento River", "royalblue",
                                           if_else(CAriver$gnis_name == "San Joaquin River","royalblue", "lightgrey")), alpha=.5) +
   #geom_sf( data = CArez, color= "darkgrey", alpha=.25) +
     # geom_sf( data = CAdelta, color= "darkgrey", alpha=.25) +
   geom_point(aes(x = long, y = lat, labels=name), data = subset(locs,ref %in% c("reciever", "hatchery")),
 alpha = .5, color="darkred", size = 3)+
  ggrepel::geom_label_repel(data=subset(locs,ref %in% c("reciever", "hatchery")), aes(x=long, y=lat, label =name), min.segment.length = 0)+
   annotate("text", x = -121.4944, y = 38.5816, label = "*")+
   # geom_segment(subset(locs,ref %in% c("dam")), aes(x=long, y=lat, color = name))+
   theme_bw() +
   ditch_the_axes+
  coord_sf(xlim = c(-124.5, -119.0),  ylim = c(37.5,42))

 #next add coordinated of spots and possibly just highlight sacramento river and add delta?

summary(as.factor(CAriver$gnis_name))
```




---- fails

ggmap
```{r}
#library(pacman)
library(tidyverse)
library(broom)
library(sf)
library(here)

#API:AIzaSyB1yH9_NxoAbr-FxflaXWZXSbrwfjPLXZg
#register_google(key = "AIzaSyB1yH9_NxoAbr-FxflaXWZXSbrwfjPLXZg", write = TRUE)

CAwater<-st_read(dsn = here("NHD_Major_Rivers"))
CAriver<-st_zm(CAwater, drop = T, what = "ZM")
#plot river data
ggplot() +
  geom_sf(mapping = aes(colour = mainpath), data = CAriver) +
  coord_sf()
#transform coordinates to match google WGS84---not working still
CAriver.crs<- st_transform(CAriver,
CRS("+proj=longlat +datum=WGS84"))

st_coordinates(CAriver.crs)

CAwater
class(CAwater)
st_crs(CAwater)
#Geodetic CRS:  NAD83 + NAVD88 height
#+init=epsg:4121 +proj=longlat +ellps=GRS80 +datum=GGRS87 +no_defs +towgs84=-199.87,74.79,246.62
#+init=
proj4string()
#issue here--- need to look into changing from sp to CRS that sets lat/long for polygon

#set zoom level
RBDD<-"Redd Bluff Diversion Dam"
RBDD<-c(lat = 40.1532, lon= -122.2028)
RBDD<-c(-124,37,-119,42)
geocode("Redd Bluff Diversion Dam")

DeltaMap<-get_map(location = RBDD, source="stamen", maptype = "terrain", color = "bw", crop=F)
ggmap(DeltaMap) + geom_sf(mapping = aes(color=mainpath), data = CAriver.crs) +
  coord_sf()



```

```{r}
library(tigris)
library(tmap)

rivers<-linear_water("CA", "Sacramento")
tm_shape(rivers) +
  tm_lines()
```



```{r}
library(tidyverse)
library(raster)
library(rgdal)
library(sp)

devtools::install_github("paleolimbot/ggspatial")

rivers<-rgdal::readOGR(dsn = here("NHD_Major_Rivers"))
#change projectoion
shpData <- spTransform(rivers,
CRS("+proj=longlat +datum=WGS84"))

DeltaMap<-get_map(location = RBDD, source="stamen", maptype = "terrain", color = "bw", crop=F)
ggmap(DeltaMap) + geom_polygon(aes(fill=Shape_Leng),
data = shpData, color ="white",
alpha = .4, linewidth = .2)


#river.ras<-raster::shapefile(here("NHD_Major_Rivers/NHD_Major_Rivers.shp"))

ggplot2::geom_



```

