
library(ggplot2)
library(plyr)
library(reshape)
library(scales)

winterWithDate <- read.csv("Winter_AllYears.csv")
winterWithDate

# Select the last 7 years of data only
lastcol <- length(winterWithDate)
fromcol <- length(winterWithDate)-6
winterWithDate <- winterWithDate[,c(1,fromcol:lastcol)]
#winterWithDate <- within(winterWithDate,rm(BY2003))
# Extract the first and last colum names to caption the graphic dynamically
 winterWithDate
# Make a replica of dataset and melt it to get summed totals for each panel
melted <- winterWithDate
total_m <- melt(melted,id='week');head(total_m) ;str(total_m)
totals <- ddply(total_m,"variable",summarise,total=sum(as.numeric(value),na.rm=T));totals

 # The year (first column) MUST be named 'variable' so that it can match the other column named 'variable'
 # generated by wintermelt below
#names(totals) <- c('variable','total')

# add one row at beginning of dataset to create the Date dummy variable
one <- winterWithDate
 #one <- one[52,] # add a row at the bottom when weeks aren't showing correctly on graph
 one <- one[1,]
 winterWithDate <- rbind(one,winterWithDate)

  firstyear <- winterWithDate[length(names(winterWithDate))-6]
   firstyear <- names(firstyear)
  firstyear <- gsub("\\D","",firstyear)
 xlab <- paste("July 1",firstyear,paste("to present")) ;xlab
# Using Dates for the X axis
winterWithDate$Date <- seq(as.Date("2008-07-1"),as.Date("2009-06-30"),by="7 days")

# Extract a date to use as a reference for the total summed value on the plot area
xloc <- winterWithDate[44,9]
xloc

wintermelt <- melt(winterWithDate,id=c("week","Date"))
winter <- ggplot(wintermelt,aes(Date,as.numeric(value)/1000,colour=variable)) +
geom_line(size=1) + theme_bw() +   # overrides all colors and axis formatting
 scale_x_date(labels= date_format("%b"),breaks = "1 month", minor_breaks = "2 week",expand=c(0,0))  +
 #scale_x_date(major="month", minor="2 weeks", format="%b",expand=c(0,0))  +
#scale_y_continuous(breaks=c(100,250,500,750,1000,1500,2000)) +
ggtitle("Juvenile Winter Chinook Salmon Estimated Passage") + theme(legend.position="none",
axis.text.x = element_text(angle=45,hjust=1,size=8.2,colour="gray50"),
axis.text.y=element_text(size=8.2,hjust=1,colour="grey50"),
axis.title.x=element_text(size=9.0),axis.title.y=element_text(size=9.0,angle=90)) +
geom_text(aes(x=xloc,y=800,label=paste("n = ", comma(total))),data=totals,inherit.aes=FALSE,size=3) +
facet_grid(variable~.) + labs(y="Number of individuals X 1,000",x=paste("\nFigure 1. Weekly estimated passage of juvenile winter Chinook Salmon at Red Bluff Diversion Dam (RK391),\nby brood-year (BY). Fish were sampled using rotary-screw traps for the period",xlab,paste(".")))

win.metafile(filename="RExcelWinter.wmf",width=9.0,height=6.0,pointsize=7)
 print(winter)
 dev.off()
 
 ######SPRING RUN
springWithDate <- read.csv("Spring_AllYears.csv")
 springWithDate

# Select the last 7 years of data only
 lastcol <- length(springWithDate)
fromcol <- length(springWithDate)-6
springWithDate <- springWithDate[,c(1,fromcol:lastcol)]

# Make a replica of dataset and melt it to get summed totals for each panel
melted <- springWithDate
total_m <- melt(melted,id='week');total_m
totals <- ddply(total_m,"variable",summarise,total=sum(as.numeric(value),na.rm=T));totals
 # The year (first column) MUST be named 'variable' so that it can match the other column named 'variable'
 # generated by springmelt below
#names(totals) <- c('variable','total')

 # add one row at beginning of dataset to create the Date dummy variable
one <- springWithDate
 one <- one[1,]
 springWithDate <- rbind(one,springWithDate)

  firstyear <- springWithDate[length(names(springWithDate))-6]
   firstyear <- names(firstyear)
  firstyear <- gsub("\\D","",firstyear)
 xlab <- paste("October 16",firstyear,paste("to present")) ;xlab
# Using Dates for the X axis
springWithDate$Date <- seq(as.Date("2008-10-16"),as.Date("2009-10-15"),by="week")
 springWithDate
# Extract a date to use as a reference for the total summed value on the plot area
xloc <- springWithDate[44,9]
xloc

springmelt <- melt(springWithDate,id=c("week","Date"))
spring <- ggplot(springmelt,aes(Date,as.numeric(value)/1000,colour=variable)) + geom_line(size=1) + theme_bw() +
   scale_x_date(labels= date_format("%b"),breaks="month",expand=c(0,0))  +
 #scale_x_date(labels= date_format("%b"),breaks = "1 month", minor_breaks = "2 weeks",expand=c(0,0))  +
ggtitle("Juvenile Spring Chinook Salmon Estimated Passage") + theme(legend.position="none",
axis.text.x = element_text(angle=45,hjust=1,size=8.2,colour="gray50"),
axis.text.y=element_text(size=8.2,hjust=1,colour="grey50"),
axis.title.x=element_text(size=9.0),axis.title.y=element_text(size=9.0,angle=90)) +
geom_text(aes(x=xloc,y=140,label=paste("n = ", comma(total))),data=totals,inherit.aes=FALSE,size=3) +
facet_grid(variable~.) + labs(y="Number of individuals X 1,000",x=paste("\nFigure 2. Weekly estimated passage of juvenile Spring Chinook Salmon at Red Bluff Diversion Dam (RK391),\nby brood-year (BY). Fish were sampled using rotary-screw traps for the period",xlab,paste(".")))

win.metafile(filename="RExcelSpring.wmf",width=9.0,height=6.0,pointsize=7)
 print(spring)
 dev.off()

   #####RBT
 rbtWithDate <- read.csv("RBT_AllYears.csv")
 rbtWithDate
 
  # Select the last 7 years of data only
lastcol <- length(rbtWithDate)
fromcol <- length(rbtWithDate)-6
rbtWithDate <- rbtWithDate[,c(1,fromcol:lastcol)]

# Make a replica of dataset and melt it to get summed totals for each panel
melted <- rbtWithDate
total_m <- melt(melted,id='week');total_m
totals <- ddply(total_m,"variable",summarise,total=sum(as.numeric(value),na.rm=T));totals
 # The year (first column) MUST be named 'variable' so that it can match the other column named 'variable'
 # generated by rbtmelt below
#names(totals) <- c('variable','total')

 rbtWithDate <- rbtWithDate[1:52,]  #Ensure that the dataset always have 52 records
# add one row at beginning of dataset to create the Date dummy variable
one <- rbtWithDate
 one <- one[1,]
 rbtWithDate <- rbind(one,rbtWithDate)
 
# Extract the first and last colum names to caption the graphic dynamically
  firstyear <- rbtWithDate[length(names(rbtWithDate))-6]
   firstyear <- names(firstyear)
  firstyear <- gsub("\\D","",firstyear)
 xlab <- paste("January 1",firstyear,paste("to present")) ;xlab
rbtWithDate$Date <- seq(as.Date("2008-1-1"),as.Date("2008-12-31"),by="week")

# Extract a date to use as a reference for the total summed value on the plot area
xloc <- rbtWithDate[44,9]
xloc

rbtmelt <- melt(rbtWithDate,id=c("week","Date"))
rbt <- ggplot(rbtmelt,aes(Date,as.numeric(value)/1000,colour=variable)) + geom_line(size=1) + theme_bw() +
   scale_x_date(labels= date_format("%b"),breaks="month",expand=c(0,0))  +
ggtitle(expression(paste(bold("Juvenile"), bolditalic(" Onchorhyncus mykiss"),bold(" Estimated Passage")))) +
theme(legend.position="none",axis.text.x = element_text(angle=45,hjust=1,size=8.2,colour="grey50"),
axis.text.y=element_text(size=8.2,hjust=1,colour="grey50"),
axis.title.x=element_text(size=9.0),axis.title.y=element_text(size=9.0,angle=90)) +
geom_text(aes(x=xloc,y=18,label=paste("n = ", comma(total))),data=totals,inherit.aes=FALSE,size=3) +
facet_grid(variable~.) + labs(y="Number of individuals X 1,000",x=paste("\nFigure 3. Weekly estimated passage of juvenile Rainbow/Steelhead trout at Red Bluff Diversion Dam (RK391),\nby brood-year (BY). Fish were sampled using rotary-screw traps for the period",xlab,paste(".")))

win.metafile(filename="RExcelRBT.wmf",width=9.0,height=6.0,pointsize=7)
 print(rbt)
 dev.off()
#facet_grid(variable~.) + labs(y="Number of individuals X 1,000",x=expression(paste("Figure 3. Weekly estimated passage of juvenile", italic(" Onchorhyncus mikiss"), " at Red Bluff Diversion Dam (RK391),by brood-year (BY).")))


   ###### FALL RUN
fallWithDate <- read.csv("Fall_AllYears.csv")
fallWithDate

# Select the last 7 years of data only
lastcol <- length(fallWithDate)
fromcol <- length(fallWithDate)-6
fallWithDate <- fallWithDate[,c(1,fromcol:lastcol)]

# Make a replica of dataset and melt it to get summed totals for each panel
melted <- fallWithDate
total_m <- melt(melted,id='week');total_m
totals <- ddply(total_m,"variable",summarise,total=sum(as.numeric(value),na.rm=T));totals
 # The year (first column) MUST be named 'variable' so that it can match the other column named 'variable'
 # generated by fallmelt below
#names(totals) <- c('variable','total')

# add one row at beginning of dataset to create the Date dummy variable
one <- fallWithDate
 one <- one[1,]
 fallWithDate <- rbind(one,fallWithDate)

# Extract the first and last colum names to caption the graphic dynamically
  firstyear <- fallWithDate[length(names(fallWithDate))-6]
   firstyear <- names(firstyear)
  firstyear <- gsub("\\D","",firstyear)
 xlab <- paste("December 1",firstyear,paste("to present")) ;xlab
 fallWithDate$Date  <-  seq(as.Date("2010-11-28"), as.Date("2011-11-30"),by="7 days")
 
# Extract a date to use as a reference for the total summed value on the plot area
xloc <- fallWithDate[44,9]
xloc
 
fallmelt <- melt(fallWithDate,id=c("week","Date"))
fall <- ggplot(fallmelt,aes(Date,as.numeric(value)/1000,colour=variable)) + geom_line(size=1) + theme_bw() +
   scale_x_date(labels= date_format("%b"),breaks="month",expand=c(0,0))  +
ggtitle("Juvenile Fall Chinook Salmon Estimated Passage") + theme(legend.position="none",
axis.text.x = element_text(angle=45,hjust=1,size=8.2,colour="gray50"),
axis.text.y=element_text(size=8.2,hjust=1,colour="grey50"),
axis.title.x=element_text(size=9.0),axis.title.y=element_text(size=9.0,angle=90)) +
geom_text(aes(x=xloc,y=2500,label=paste("n = ", comma(total))),data=totals,inherit.aes=FALSE,size=3) +
facet_grid(variable~.) + labs(y="Number of individuals X 1,000",x=paste("\nFigure 4. Weekly estimated passage of juvenile Fall Chinook Salmon at Red Bluff Diversion Dam (RK391),\nby brood-year (BY). Fish were sampled using rotary-screw traps for the period",xlab,paste(".")))

win.metafile(filename="RExcelFall.wmf",width=9.0,height=6.0,pointsize=7)
 print(fall)
 dev.off()
 

     ##### LATE_FALL RUN
  latefallWithDate <- read.csv("LateFall_AllYears.csv")
  latefallWithDate
  
 # Select the last 7 years of data only
  lastcol <- length(latefallWithDate)
fromcol <- length(latefallWithDate)-6
latefallWithDate <- latefallWithDate[,c(1,fromcol:lastcol)]
  
 # Make a replica of dataset and melt it to get summed totals for each panel
melted <- latefallWithDate
total_m <- melt(melted,id='week');total_m
totals <- ddply(total_m,"variable",summarise,total=sum(as.numeric(value),na.rm=T));totals
 # The year (first column) MUST be named 'variable' so that it can match the other column named 'variable'
 # generated by latefallmelt below
#names(totals) <- c('variable','total')
  
  # add one row at beginning of dataset to create the Date dummy variable
one <- latefallWithDate
 one <- one[1,]
 latefallWithDate <- rbind(one,latefallWithDate)

# Extract the first and last colum names to caption the graphic dynamically
  firstyear <- latefallWithDate[length(names(latefallWithDate))-6]
   firstyear <- names(firstyear)
  firstyear <- gsub("\\D","",firstyear)
 xlab <- paste("April 1",firstyear,paste("to present")) ;xlab
latefallWithDate$Date <- seq(as.Date("2008-4-1"),as.Date("2009-3-31"),by="week")

# Extract a date to use as a reference for the total summed value on the plot area
xloc <- latefallWithDate[44,9]
xloc

latefallmelt <- melt(latefallWithDate,id=c("week","Date"))
latefall <- ggplot(latefallmelt,aes(Date,as.numeric(value)/1000,colour=variable)) + geom_line(size=1) + theme_bw() +
   scale_x_date(labels= date_format("%b"),breaks="month",expand=c(0,0))  +
ggtitle("Juvenile Late Fall Chinook Salmon Estimated Passage") + theme(legend.position="none",
axis.text.x = element_text(angle=45,hjust=1,size=8.2,colour="gray50"),
axis.text.y=element_text(size=8.2,hjust=1,colour="grey50"),
axis.title.x=element_text(size=9.0),axis.title.y=element_text(size=9.0,angle=90)) +
geom_text(aes(x=xloc,y=90,label=paste("n = ", comma(total))),data=totals,inherit.aes=FALSE,size=3) +
facet_grid(variable~.) + labs(y="Number of individuals X 1,000",x=paste("\nFigure 5. Weekly estimated passage of juvenile Late Fall Chinook Salmon at Red Bluff Diversion Dam (RK391),\nby brood-year (BY). Fish were sampled using rotary-screw traps for the period",xlab,paste(".")))

win.metafile(filename="RExcelLateFall.wmf",width=9.0,height=6.0,pointsize=7)
 print(latefall)
 dev.off()
 

   #### ALL RUNS
  AllRunsWithDate <- read.csv("AllRuns.csv")
  AllRunsWithDate
  
 # Select the last 7 years of data only
lastcol <- length(AllRunsWithDate)
fromcol <- length(AllRunsWithDate)-6
AllRunsWithDate <- AllRunsWithDate[,c(1,fromcol:lastcol)]
  
  # Make a replica of dataset and melt it to get summed totals for each panel
melted <- AllRunsWithDate
total_m <- melt(melted,id='IDWeek');total_m
totals <- ddply(total_m,"variable",summarise,total=sum(as.numeric(value),na.rm=T));totals
 # The year (first column) MUST be named 'variable' so that it can match the other column named 'variable'
 # generated by AllRunsmelt below
#names(totals) <- c('variable','total')

   # add one row at beginning of dataset to create the Date dummy variable
  one <- AllRunsWithDate
 one <- one[1,]
 AllRunsWithDate <- rbind(one,AllRunsWithDate)

# Extract the first and last colum names to caption the graphic dynamically
  firstyear <- AllRunsWithDate[length(names(AllRunsWithDate))-6]
   firstyear <- names(firstyear)
  firstyear <- gsub("\\D","",firstyear)
  lastyear <-  AllRunsWithDate[length(names(AllRunsWithDate))]
   lastyear <- names(lastyear)
  lastyear <- gsub("\\D","",lastyear)
  xlab <- paste("January 1",firstyear,paste("to December 31",lastyear))
AllRunsWithDate$Date <- seq(as.Date("2008-1-1"),as.Date("2008-12-31"),by="week")

# Extract a date to use as a reference for the total summed value on the plot area
xloc <- AllRunsWithDate[44,9]
xloc

AllRunsmelt <- melt(AllRunsWithDate,id=c("IDWeek","Date"))
AllRuns <- ggplot(AllRunsmelt,aes(Date,as.numeric(value)/1000,colour=variable)) + geom_line(size=1)+ theme_bw() +
   scale_x_date(labels= date_format("%b"),breaks="month",expand=c(0,0))  +
ggtitle("Weekly Estimated Chinook Passage at Red Bluff Diversion Dam - All Runs Combined") + theme(legend.position="none",
axis.text.x = element_text(angle=45,hjust=1,size=8.2,colour="gray50"),
axis.text.y=element_text(size=8.2,hjust=1,colour="grey50"),
axis.title.x=element_text(size=9.0),axis.title.y=element_text(size=9.0,angle=90)) +
geom_text(aes(x=xloc,y=2500,label=paste("n = ", comma(total))),data=totals,inherit.aes=FALSE,size=3) +
facet_grid(variable~.) + labs(y="Number of individuals X 1,000",x=paste("\nFigure 6. Weekly estimated passage of juvenile Chinook Salmon at Red Bluff Diversion Dam (RK391),\nby calendar year. Fish were sampled using rotary-screw traps for the period",xlab))

win.metafile(filename="RExcelAllRuns.wmf",width=9.0,height=6.0,pointsize=7)
 print(AllRuns)
dev.off()


# winter <- read.csv("Winter_AllYears.csv")
#winter <- winter[-53,] # Remove last row but keep 53 rows when using 'Date' along X axis
#Nice for ordering the X axis variable
#winter$week <- ordered(winter$week,levels=c(27:52,1:26))
#winter$week # see the levels that were just created
#winter$WEEK <- 1:52
#wintermelt <- melt(winter,id=c("week","WEEK"))
#print(ggplot(wintermelt,aes(WEEK,value/1000,colour=variable)) + geom_line(size=1)+
# scale_x_continuous(breaks=seq(1,52,2),labels=levels(winter$week)[seq(1,52,2)],) +
# facet_grid(variable~.) + opts(title="Juvenile Winter Chinook Salmon Estimated Passage",legend.position="none") +
 #labs(y="Number of individuals X 1,000",x="WEEK"))




#latefall <- read.csv("LateFall_AllYears.csv")
#latefallmelt <- melt(latefall,id="week")
#latefall <- ggplot(latefallmelt,aes(week,value/1000)) + geom_line(aes(colour=variable))+ opts(legend.position="none") +
#facet_wrap(~variable,ncol=2) + opts(title="Late Fall") + labs(y="Number of fish X 1,000",x="WEEK")
#win.metafile(filename="RExcelLateFall.wmf",width=9.0,height=6.0,pointsize=7)
 #print(latefall)
# dev.off()



#rbt <- read.csv("RBT_AllYears.csv")
#rbtmelt <- melt(rbt,id="week")
#rbt <- ggplot(rbtmelt,aes(week,value/1000)) + geom_line(aes(colour=variable))+ opts(legend.position="none") +
#facet_wrap(~variable,ncol=2) + opts(title="RBT") + labs(y="Number of fish X 1,000",x="WEEK")
#win.metafile(filename="RExcelRBT.wmf",width=9.0,height=6.0,pointsize=7)
# print(rbt)
 #dev.off()





